on:
  push:
    branches: [main, develop]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        env:
          url: 
            ${{secrets.RENDER_HOOK}}
        run: |
          curl "$url"
          
