on:
  push:
    branches: [feature/update-database-population]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4
      - name: Build and Run Tests
        uses: pybuilder/build@master
      - name: Deploy
        env:
          url:
            ${{secrets.RENDER_HOOK}}
        run: |
          curl "$url"
          
