on:
  push:
    branches: [main, develop]

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Application Code
        uses: actions/checkout@v4
      - name: Install Python and Dependencies
        uses: actions/setup-python@v5
        with:
          python-version: 3.12
          run: |
            python pip install -r  requirements.txt
      - name: Build and Run Tests
        uses: pybuilder/build@master
      - name: Deploy
        env:
          url:
            ${{secrets.RENDER_HOOK}}
        run: |
          curl "$url"
          
